/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estoque;

import principal.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author igorn
 */
public class JPanelCadProduto extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCadProduto
     */
    public JPanelCadProduto() {
        initComponents();
        atualizarCodProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodProduto = new javax.swing.JLabel();
        tfCodProduto = new javax.swing.JTextField();
        lbRotuloProd = new javax.swing.JLabel();
        tfRotuloProd = new javax.swing.JTextField();
        lbQtdEstoque = new javax.swing.JLabel();
        lbPrecoFabrica = new javax.swing.JLabel();
        tfPrecoFabrica = new javax.swing.JTextField();
        lbPrecoVenda = new javax.swing.JLabel();
        tfPrecoVenda = new javax.swing.JTextField();
        lbDescProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescProd = new javax.swing.JTextArea();
        btCancelar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        spQtdEstoque = new javax.swing.JSpinner();

        lbCodProduto.setText("Cód:");

        tfCodProduto.setEditable(false);
        tfCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodProdutoActionPerformed(evt);
            }
        });

        lbRotuloProd.setText("Rótulo do produto:");

        lbQtdEstoque.setText("Qtd em estoque: ");

        lbPrecoFabrica.setText("Preço de Fábrica: ");

        tfPrecoFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoFabricaActionPerformed(evt);
            }
        });

        lbPrecoVenda.setText("Preço de Venda: ");

        lbDescProd.setText("Descrição do Produto: ");

        taDescProd.setColumns(20);
        taDescProd.setRows(5);
        jScrollPane1.setViewportView(taDescProd);

        btCancelar.setText("Cancelar");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDescProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbCodProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbRotuloProd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRotuloProd))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbPrecoFabrica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrecoFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPrecoVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbQtdEstoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodProduto)
                    .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRotuloProd)
                    .addComponent(tfRotuloProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoFabrica)
                    .addComponent(tfPrecoFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoVenda)
                    .addComponent(tfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQtdEstoque)
                    .addComponent(spQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btLimpar)
                    .addComponent(btSalvar))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodProdutoActionPerformed

    private void tfPrecoFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoFabricaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoFabricaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (validarCampos() == false){
            JOptionPane.showMessageDialog(null, "Os valores não foram salvos devido a campos inválidos.");
        }
        else {
            salvarProduto();
            limparCampos();
            atualizarCodProduto();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private boolean validarCampos() {
        int valSpinner;
        
        try { 
            Float.parseFloat(tfPrecoFabrica.getText());
        } catch ( NumberFormatException e ) {
            JOptionPane.showMessageDialog(null, "Formato do preço de fábrica inválido!");
            return false;
        }
        try { 
            Float.parseFloat(tfPrecoVenda.getText());
        } catch ( NumberFormatException e ) {
            JOptionPane.showMessageDialog(null, "Formato do preço de venda inválido!");
            return false;
        }
        try {
            valSpinner = (Integer)spQtdEstoque.getValue();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Campo de quantidade de estoque inválido");
            return false;
        }
        
        return true;
    }
    
    private void salvarProduto(){
        Produto prod = new Produto();
        
        //O CommitEdit() atualiza o valor do Spinner. Sem ele, o valor passado pro setQtdEstoque() fica inconsistente.
        try {
            spQtdEstoque.commitEdit();
        } catch ( java.text.ParseException e ) {
            
        }
        
        prod.setRotulo(tfRotuloProd.getText());
        prod.setPrecoFabrica(Float.parseFloat(tfPrecoFabrica.getText()));
        prod.setPrecoVenda(Float.parseFloat(tfPrecoVenda.getText()));
        prod.setQtdEstoque((Integer)spQtdEstoque.getValue());
        prod.setDescricao(taDescProd.getText());
        
        Principal.estoque.add(prod);
        
        JOptionPane.showMessageDialog(null, "Produto salvo com sucesso!");
    }
    
        private void limparCampos() {
            tfPrecoFabrica.setText("");
            tfPrecoVenda.setText("");
            tfRotuloProd.setText("");
            taDescProd.setText("");
            spQtdEstoque.setValue(0);
        }
        
        private void atualizarCodProduto(){
            tfCodProduto.setText(String.valueOf(Principal.estoque.size() + 1));
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodProduto;
    private javax.swing.JLabel lbDescProd;
    private javax.swing.JLabel lbPrecoFabrica;
    private javax.swing.JLabel lbPrecoVenda;
    private javax.swing.JLabel lbQtdEstoque;
    private javax.swing.JLabel lbRotuloProd;
    private javax.swing.JSpinner spQtdEstoque;
    private javax.swing.JTextArea taDescProd;
    private javax.swing.JTextField tfCodProduto;
    private javax.swing.JTextField tfPrecoFabrica;
    private javax.swing.JTextField tfPrecoVenda;
    private javax.swing.JTextField tfRotuloProd;
    // End of variables declaration//GEN-END:variables
}
